
defaults: &defaults
  adapter: postgresql
  username: developer
  password: developer99
  host: localhost

development:
  database: tracking_development
  <<: *defaults

test:
  database: tracking_test
  <<: *defaults

production:
  database: tracking_production
  <<: *defaults
