
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: railguide48
  password: 9084ediugliar
  host: localhost

development: 
  database: development_alloc
  <<: *defaults

test:
  database: alloc
  <<: *defaults

production:
  database: production_alloc
  <<: *defaults
